### ISSUE TITLE
Скласти додаткові інформаційні блоки

### ISSUE THREAD

**Issue by vilderly** [vilderly/homepage#7]
Можна зробити резюме менш формальним, додавши додаткові блоки, які містять корисну інформацію, але подають її в "розважальній" формі. Наприклад, що подобається і не подобається, сильні і слабкі сторони, перелік навиків чи хобі, інфографіка або ж інтерактивні модулі, тощо. Варто написати контент такого блоку раніше, ніж починати верстку, бо його розміри впливатимуть на розміщення елементів на сторінці.

**Comment by oleh-yanichko** [comment]
A special counsel investigation led by Robert Mueller found that Trump benefited from Russian interference in the 2016 presidential election, but did not find sufficient evidence to establish criminal conspiracy or coordination with Russia.[b] Mueller also investigated Trump for obstruction of justice and neither indicted nor exonerated him. The House of Representatives impeached Trump in December 2019 for abuse of power and obstruction of Congress after he solicited Ukraine to investigate Joe Biden. The Senate acquitted him of both charges in February 2020.

Trump lost the 2020 presidential election to Biden, but refused to concede defeat. He attempted to overturn the results by making false claims of electoral fraud, pressuring government officials, mounting scores of unsuccessful legal challenges and obstructing the presidential transition. On the day Congress met to tally the electoral votes, January 6, 2021, Trump rallied his supporters and urged them to march to the Capitol. Many arrived before he concluded his speech; hundreds broke through security barricades and violently stormed the Capitol, forcing Congress to evacuate. After police had cleared the Capitol of rioters, Congress returned and certified Joe Biden as the winner of the election. Seven days later, the House impeached Trump for incitement of insurrection, making him the only federal officeholder in American history to be impeached twice. The Senate acquitted Trump for the second time on February 13, 2021.
